package com.fenomina.payroll_engine.enums;

public enum TipoNovedad {

    // Horas extra
    HORA_EXTRA_DIURNA_ORDINARIA,
    HORA_EXTRA_NOCTURNA_ORDINARIA,
    HORA_EXTRA_DIURNA_DOMINICAL,
    HORA_EXTRA_NOCTURNA_DOMINICAL,

    // Recargos
    RECARGO_NOCTURNO_ORDINARIO,
    RECARGO_DIURNO_DOMINICAL,
    RECARGO_NOCTURNO_DOMINICAL,

    // Incapacidades
    INCAPACIDAD_ORIGEN_COMUN,
    INCAPACIDAD_ORIGEN_LABORAL,

    // Licencias remuneradas
    LICENCIA_MATERNIDAD,
    LICENCIA_PATERNIDAD,
    LICENCIA_CALAMIDAD,
    LICENCIA_MATRIMONIO,
    LICENCIA_LEY_ISAAC,
    LICENCIA_SUFRAGIO,
    LICENCIA_CARGO_TRANSITORIO,
    LICENCIA_CITACION_JUDICIAL,
    LICENCIA_OTRO_PERMISO_REMUNERADO,

    // Licencias no remuneradas
    LICENCIA_NO_REMUNERADA,

    // Vacaciones
    VACACIONES_DISFRUTADAS,
    VACACIONES_COMPENSADAS,

    // Devengos variables
    COMISION,
    BONIFICACION_OCASIONAL,
    BENEFICIO_EXTRALEGAL,
    OTRO_DEVENGO_SALARIAL,
    OTRO_DEVENGO_NO_SALARIAL,

    // Deducciones
    RETENCION_FUENTE,
    OTRO_DESCUENTO_SALARIAL,
    OTRO_DESCUENTO_NO_SALARIAL
}
